data:
  data_name: 'test'
  dataset:  # test dataset
    name: pl
    path: ./data/crossdocked_pocket10
    split: ./data/split_by_name.pt

model:
    checkpoint: ./ckpt/pretrained_Pocket2Mol.pt

sample:
  seed: 2020
  mask_init: True
  num_samples: 100
  beam_size: 500
  max_steps: 50
  threshold:
    focal_threshold: 0.5
    pos_threshold: 0.25
    element_threshold: 0.3
    hasatom_threshold: 0.6
    bond_threshold: 0.4